### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by re-coded** [tomayac/local-reverse-geocoder#21]
Hello Thomas, 
I received and error while trying to run a script.

--------------
user@localhost:~ /sources/nodejs/reverse1$ npm -v
3.5.2
user@localhost:~ /sources/nodejs/reverse1$ nodejs -v
v4.2.6
user@localhost:~ /sources/nodejs/reverse1$ nodejs reverse3.js 
/home/user/sources/nodejs/reverse1/node_modules/csv-parse/lib/index.js:114
Parser = function(options = {}) {
                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/sources/nodejs/reverse1/node_modules/local-reverse-geocoder/geocoder.js:35:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
user@localhost:~/sources/nodejs/reverse1$ cat reverse3.js 
var geocoder = require('local-reverse-geocoder');
var point = {latitude: 42.083333, longitude: 3.1};
geocoder.lookUp(point, 1, function(err, res) {
  console.log(JSON.stringify(res, null, 2));
});

user@localhost:~ /sources/nodejs/reverse1$  

--------------

Thanks in advance.

**Comment by tomayac** [comment]
Sorry for the long turn-around time. The csv-parse package [makes use](https://github.com/adaltas/node-csv-parse/blob/b8f3d5f6cc18ea54b00059bf5501a11271f7d531/lib/index.js#L114) of [default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters), which is [not supported](http://node.green/#ES2015-syntax-default-function-parameters) in your version (v4.2.6) of Node.js yet. Recommendation: update to a more recent Node.js version.
